### ISSUE TITLE
Taxa formatting

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/supersead#15]
* Change Taxa Format: "Family, Genus Species"
 - Endast för insekter, lägg även till author format blir då: "Family, Genus Species Author" - author finns inte alltid men lägg till om det finns

 Also take in account the "abundance ident" data/levels

Format if record has identification levels:
1 Family, 2 Genus 3 species
If identification_level_name = "c.f. Family" or "Family" then
	replace 1 with "cf."+<Family>
	If identification_level_name = "c.f. Genus" or "Genus" then
	replace 2 with "cf."+<Genus>
	If identification_level_name = "c.f. Species" or "Species" then
	replace 3 with "cf."+<Species>

	e.g. Poaceae, Avena cf. sativa (if c.f. Species)
e.g. Poaceae, cf. Avena sativa (if c.f. Genus)

Genus and Species should be written in italics (but not Family or other)

* For plant samples: Move "Family" out to a separate column and make it hidden by default but expandable (somehow), for everything else Family is not a separate column but part of the parsed name

**Comment by johanvonboer** [comment]
@visead How do I know if something is a plant based on the sead taxa?

**Comment by visead** [comment]
You don’t, unless it has a plant based analysis method. This is more than a structural issue, as pollen and plant macrofossils come from the same organisms, but are completely different analysis methods…

________________________________________________
Dr. Philip Buckland<http://www.idesam.umu.se/om/personal/arkeologi/philip-buckland/>
Senior Lecturer in Environmental Archaeology
Fellow of the Royal Entomological Society
Director of the SEAD Project<http://www.sead.se/>
Director of the Environmental Archaeology Lab.<http://www.idesam.umu.se/english/mal>
Dept. Historical, Philosophical and Religious Studies<http://www.idesam.umu.se/english/>

Umeå universitet / Umeå University
SE-901 87 Umeå, Sweden
Tel: +46 (0)90 786 5292       Mob: +46 (0)738 321 131
När du skickar e-post till Umeå universitet så innebär detta att Umeå universitet behandlar dina personuppgifter. För att läsa mer om hur detta går till, gå till umu.se/gdpr
By sending an email to Umeå University, the University will need to process your personal data. For more information, please read umu.se/en/gdpr

**Comment by johanvonboer** [comment]
Good to know, I won't do anything about this for now then.
