### ISSUE TITLE
Petrographic -> Petrography

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/supersead#21]
* Portals:
	* Change: Petrographic -> Petrography

**Comment by johanvonboer** [comment]
Now that I look at this, I'm confused, because there is no such portal. So where was I supposed to change this @visead ?

**Comment by Loer0022** [comment]
It is correct that this should be petography, although, I am not sure if this will become its own portal or if it is related to the ceramics portal. I believe that it might be a confusion with the scientific laboratory method named Ceramic petrography and the portal names.

Petrography would therefore not be its own portal but is part of the Ceramics portal. So you don't need to change anything.

**Comment by johanvonboer** [comment]
@Loer0022 Thanks! Closing this
