### ISSUE TITLE
Timeline not working off-campus without VPN

### ISSUE THREAD

**Issue by visead** [humlab-sead/supersead#42]
Just tried the site at Umeå airport over Eduroam - all works except timeline area is blank.
Turned on VPN and timeline appears.

**Comment by johanvonboer** [comment]
Must be because temperature data can't be loaded, added another grant to more closely reflect how the other tables are set up:
GRANT ALL ON TABLE public.tbl_temperatures TO sead_master;

Will test from home later on.

**Comment by johanvonboer** [comment]
This is most likely fixed now, but needs to be tested.

**Comment by johanvonboer** [comment]
Test from home

**Comment by johanvonboer** [comment]
@visead Test!

**Comment by visead** [comment]
Tested from home. 
Works as expected.
Remember to test after next pre-release.
