### ISSUE TITLE
Viewstate loading fails

### ISSUE THREAD

**Issue by visead** [humlab-sead/supersead#66]
Saved viewstates do not load any data or facets or data.
E.g. http://supersead.humlab.umu.se/viewstate/TPfcPwQP 

![image](https://user-images.githubusercontent.com/35995002/72445160-92cf0000-37b1-11ea-8c4a-b0accbe1eb1c.png)

**Comment by johanvonboer** [comment]
Note to self: Viewstate loading fails when trying to load browser-saved viewstates, since the new implementation only looks serverside for viewstates.
