### ISSUE TITLE
Dendro dating

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/supersead#79]
Should be added:

QUERY:

select ps.sample_name as “Sample”, at.age_type as “Age_type”, dd.age_older as “Older”, dd.age_younger as “Younger”, dd.error_plus as “Plus”, dd.error_minus as “Minus“, eu.error_uncertainty_type as “Error_uncertainty”, soq.season_or_qualifier_type as “Season”
 
from tbl_physical_samples ps
join tbl_analysis_entities ae on ps.physical_sample_id = ae.physical_sample_id
join tbl_dendro_dates dd on ae.analysis_entity_id = dd.analysis_entity_id
left join tbl_season_or_qualifier soq on soq.season_or_qualifier_id = dd.season_or_qualifier_id
left join tbl_age_types at on at.age_type_id = dd.age_type_id
left join tbl_error_uncertainties eu on eu.error_uncertainty_id = dd.error_uncertainty_id
 
order by 1

**Comment by johanvonboer** [comment]
Added intital implementation on supersead. Awaiting feedback from Mattias.

**Comment by MattiasSealander** [comment]
The format works well for, seemingly, the majority of the samples. One exception, which features a date with an error which also has an uncertainty added, has some formating issue.

Site ID 2019, name: Jät Kyrka. Sample 75116.

**Comment by johanvonboer** [comment]
Dendro dating implemented
