### ISSUE TITLE
Review text in About-box

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/supersead#82]
The text in the About-box on supersead is just copied straight over from qsead, it might need some editing.

**Comment by visead** [comment]
New text. File with html links attached (note links not tested as fecking MS Word is now crashing when I click a link from Word. I blame Edge for being slow and timing Word out. _Rant over_). 
[Supersead about text 20200326.docx](https://github.com/humlab-sead/supersead/files/4388559/Supersead.about.text.20200326.docx)

> SEAD is a national research infrastructure for Swedish archaeological science and an international database for environmental archaeology and Quaternary science data. It is hosted by the Environmental Archaeology Lab (MAL) and Humlab at Umeå University, Sweden. 
> As well as providing sustainable data storage, SEAD facilitates the analysis, visualisation and extraction of data on past climates, environments and human impacts, and forms part of an international network of research infrastructure for archaeology, Quaternary palaeoecology and biodiversity studies. Our mission is to provide easy access to data and online tools to aid interdisciplinary, international research which goes beyond the original purpose of the data.
> SEAD includes online access to the BugsCEP palaeoentomology database. Further digitization and development is ongoing in partnership with the National laboratory for wood anatomy and dendrochronology at Lund University, the Archaeological Research Lab, Stockholm University, SKEA (Stilborg Keramikanalys), and other organisations in Sweden. Legacy data are included from The Laboratory for Ceramic Research, Lund. Future development plans include integration with the Swedish National Heritage Board's information systems and the capacity to serve as a data source for any system. 
> SEAD is the official database infrastructure of the ArchLab Consortium of Archaeological Research Laboratories, and a partner in infrastructures for palaeoecology (Neotoma Paleoecology Database and Community), semantic networking and long-term human ecodynamics (dataARC cyberinfrastructure), archaeological data (ARIADNE+), heritage science (IPERION-HS, Heritage Science Sweden) and biodiversity science (SBDI - Swedish Biodiversity Data Infrastructure).
> SEAD has been financed by the Swedish Foundation for Humanities and Social Sciences (VISEAD project), Swedish Research Council, Umeå University, Umeå University Faculty of Arts and Humanities, the Department of Historical, Philosophical & Religious Studies, and Lund University. 
> SEAD is always interested in hearing from anyone, including students and interns, wishing to undertake projects involving the database. Please contact the team should you wish to make your data available through the system, or work with us in any other capacity. 
> All data in the SEAD database is freely available and licensed under the Creative Commons Attribution 4.0 International licence.
