### ISSUE TITLE
Filter results are being added to map rather than map showing restricted results?

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/supersead#88]
filter results are being added to map rather than map showing restricted results

**Comment by johanvonboer** [comment]
@visead I need some help with replicating this, what filters are you using?

**Comment by johanvonboer** [comment]
Might be fixed now if this was the same as #89? @visead

**Comment by visead** [comment]
Did a quick testing and it appears to be fixed now. 
Can we have a very brief description of what the cause was?

**Comment by johanvonboer** [comment]
Of course - it would be my pleasure to bore you with the technical details! :)

During a refactoring of this code a while ago I had used the cluster layer rendering code as a template for rendering the individual layer, and I had missed to change a place where the newly created layer was defined as "clusterPoints", to just "points". This resulted in that if you rendered the individual points and then back to the cluster points again, the system would look for a layer named "points" to delete, but there were none since it was misnamed "clusterpoints", so the individual point layer would always stay on the map once rendered, and in fact multiple copies of it would render if you repeated the procedure.

**Comment by visead** [comment]
Technical details are always a please ;)
But also useful if we encounter the problem again in the future.

________________________________________________
Dr. Philip Buckland<https://www.umu.se/en/staff/philip-buckland/>
Senior Lecturer in Environmental Archaeology
Fellow of the Royal Entomological Society
Director of the Environmental Archaeology Lab.<http://www.idesam.umu.se/english/mal>
Director of the SEAD Project<http://www.sead.se/>
Dept. Historical, Philosophical and Religious Studies<http://www.idesam.umu.se/english/>

Umeå universitet / Umeå University
SE-901 87 Umeå, Sweden
Tel: +46 (0)90 786 5292       Mob: +46 (0)738 321 131
När du skickar e-post till Umeå universitet så innebär detta att Umeå universitet behandlar dina personuppgifter. För att läsa mer om hur detta går till, gå till umu.se/gdpr
By sending an email to Umeå University, the University will need to process your personal data. For more information, please read umu.se/en/gdpr
